<x-app-layout>
    <div>
        <livewire:basic-banner/>
        <livewire:breadcrumb/>
        <livewire:tags/>
        <livewire:search/>
        <livewire:read-next/>
        <livewire:pagination/>
        <livewire:footer/>
    </div>
</x-app-layout>