<x-app-layout>
    <div>
        <livewire:banner/>
        <livewire:breadcrumb/>
        <livewire:single-videos-list/>
        <livewire:latest-videos/>
        <livewire:footer/>
    </div>
</x-app-layout>
