<x-app-layout>
    <div>
        <livewire:banner/>
        <livewire:breadcrumb/>
        <livewire:blog-content/>
        <livewire:share-blog/>
        <livewire:latest-gallery/>
        <livewire:footer/>
    </div>
</x-app-layout>